// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
{//using loops 
  const evenFibs = []
  let a = 0
  let b = 1
  while ( b < 4e6 ) {
    const c = a+b
    if (c%2 === 0) {
      evenFibs.push( c )
    }
    a = b
    b = c
  }
  console.log("using loops", evenFibs.reduce( (a,b)=> a+b ))
}
{//uinsg recusion

  const evenFibs = []
  const max = 4e6
  const nextFib = (a,b) => {
    if (b > max) return b
    const c = a+b
    if (c%2 === 0) {
      evenFibs.push( c )
    }
    return nextFib(b,c)
  }
  
  nextFib(0,1)
  console.log("using recussion", evenFibs.reduce( (a,b)=> a+b ))
}